logging:
  level:
    com.jhj.gulimall: debug
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.16.223:3306/gulimall_pms?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.16.223:8848
  application:
    name: gulimall-product
  redis:
    host: 192.168.16.223
#    password:
    port: 6379
  cache:
    #类型
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
  zipkin:
    #地址
    base-url: http://127.0.0.1:9411/
    #关闭服务注册
    discovery-client-enabled: false
    #发送模式
    sender:
      type: web
  #采样数据
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 12000
gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 1000

