spring:
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.1.104
    port: 6379
server:
  port: 20000
  servlet:
    session:
      timeout: 30m