spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.251.250:8848
  application:
    name: gulimall-search
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 13000

es:
  ip: 121.5.251.250
  port: 9200
